#!/bin/sh
cat <<EOF > /usr/share/nginx/html/env-config.js
window._env_ = {
  VITE_API_URL: "$VITE_API_URL",
  VITE_CLIENT_ID_KEYCLOAK: "$VITE_CLIENT_ID_KEYCLOAK",
  VITE_CLIENT_SECRET_KEYCLOAK: "$VITE_CLIENT_SECRET_KEYCLOAK",
  VITE_KEYCLOAK_TOKEN_URL: "$VITE_KEYCLOAK_TOKEN_URL",
  VITE_KEYCLOAK_LOGOUT_URL: "$VITE_KEYCLOAK_LOGOUT_URL",
  VITE_LOGIN_W_GG_BE: "$VITE_LOGIN_W_GG_BE"
}
EOF